# Generated by Django 5.2.12 on 2026-04-27 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model_name", models.CharField(default="qwen-plus", max_length=100)),
                ("operation", models.CharField(default="", max_length=100)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="papers/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_failed", models.BooleanField(default=False)),
                (
                    "meta_title",
                    models.CharField(blank=True, default="无", max_length=500),
                ),
                (
                    "meta_authors",
                    models.CharField(blank=True, default="无", max_length=500),
                ),
                ("meta_keywords", models.TextField(blank=True, default="无")),
                ("meta_abstract", models.TextField(blank=True, default="无")),
                (
                    "meta_journal",
                    models.CharField(blank=True, default="无", max_length=500),
                ),
                (
                    "meta_year",
                    models.CharField(blank=True, default="无", max_length=10),
                ),
                ("meta_confirmed", models.BooleanField(default=False)),
                ("knowledge_graph_data", models.JSONField(blank=True, null=True)),
                ("knowledge_graph_status", models.CharField(default="", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
